from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    HRFlowable,
)
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.colors import HexColor, white
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import A4
from datetime import datetime


def generate_student_pdf(student, filename):
    doc = SimpleDocTemplate(
        filename,
        pagesize=A4,
        rightMargin=35,
        leftMargin=35,
        topMargin=40,
        bottomMargin=35,
    )

    styles = getSampleStyleSheet()

    title = styles["Heading1"]
    title.alignment = TA_CENTER
    title.textColor = HexColor("#0d6efd")
    title.spaceAfter = 8

    subtitle = styles["Heading2"]
    subtitle.alignment = TA_CENTER
    subtitle.textColor = HexColor("#555555")
    subtitle.spaceAfter = 15

    heading = styles["Heading2"]
    heading.textColor = HexColor("#0d6efd")
    heading.spaceBefore = 10
    heading.spaceAfter = 10

    normal = styles["BodyText"]
    normal.leading = 18
    normal.spaceAfter = 8

    elements = []

    elements.append(Paragraph("EduInsight AI", title))
    elements.append(Paragraph(
        "Artificial Intelligence-Based Student Performance Prediction Report",
        subtitle,
    ))
    elements.append(
        Paragraph(
            f"Generated on: {datetime.now().strftime('%d %B %Y %I:%M %p')}",
            normal,
        )
    )
    elements.append(HRFlowable(width="100%", thickness=1,
                               color=HexColor("#0d6efd")))
    elements.append(Spacer(1, 18))

    elements.append(Paragraph("1. Student Information", heading))

    student_table = Table(
        [
            ["Student Name", student["student_name"]],
            ["Student ID", student["student_id"]],
            ["Prediction Result", student["prediction"]],
            ["Confidence Score", f"{student['confidence_score']}%"],
        ],
        colWidths=[2.3 * inch, 4.3 * inch],
    )

    student_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), HexColor("#0d6efd")),
        ("TEXTCOLOR", (0, 0), (0, -1), white),
        ("BACKGROUND", (1, 0), (1, -1), colors.whitesmoke),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
    ]))

    elements.append(student_table)
    elements.append(Spacer(1, 18))

    elements.append(Paragraph("2. Academic Performance", heading))

    performance = Table(
        [
            ["Attendance Percentage", f"{student['attendance_percentage']}%"],
            ["Study Hours per Day", f"{student['study_hours_per_day']} Hours"],
            ["Assignment Score", str(student["assignment_score"])],
            ["Midterm Examination", str(student["midterm_score"])],
            ["Final Examination", str(student["final_exam_score"])],
            ["Class Participation", str(student["participation_score"])],
            ["Average Sleep Hours", f"{student['sleep_hours']} Hours"],
        ],
        colWidths=[3.1 * inch, 3.5 * inch],
    )

    performance.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), HexColor("#198754")),
        ("TEXTCOLOR", (0, 0), (-1, 0), white),
        ("BACKGROUND", (0, 1), (-1, -1), HexColor("#f8f9fa")),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
    ]))

    elements.append(performance)
    elements.append(Spacer(1, 18))

    elements.append(Paragraph("3. AI Recommendation", heading))

    recommendation = student.get("recommendation") or "No AI recommendation available."
    recommendation = recommendation.strip()
    if len(recommendation) > 1500:
        recommendation = recommendation[:1500] + "... (continued)"

    for p in recommendation.split("\n"):
        p = p.strip()
        if p:
            elements.append(Paragraph(p, normal))

    elements.append(Spacer(1, 15))

    elements.append(Paragraph("4. Prediction Summary", heading))

    summary_table = Table(
        [
            ["Prediction Result", student["prediction"]],
            ["Confidence Score", f"{student['confidence_score']}%"],
            ["Attendance", f"{student['attendance_percentage']}%"],
            ["Prediction Model", "Support Vector Machine (SVM)"],
            ["Recommendation Engine", "Groq GPT-OSS 20B"],
            ["Generated By", "EduInsight AI"],
        ],
        colWidths=[2.8 * inch, 3.8 * inch],
    )

    summary_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), HexColor("#ffc107")),
        ("BACKGROUND", (1, 0), (1, -1), colors.whitesmoke),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
    ]))

    elements.append(summary_table)
    elements.append(Spacer(1, 18))

    elements.append(Paragraph("5. AI Interpretation", heading))

    if student["prediction"] == "High Performance":
        interpretation = ("The AI model predicts that the student is likely to achieve excellent "
                          "academic performance. Continue maintaining the current study habits.")
    elif student["prediction"] == "Moderate Performance":
        interpretation = ("The AI model predicts satisfactory academic performance with room for "
                          "improvement through consistent study, participation and attendance.")
    else:
        interpretation = (
            "The AI model predicts that the student is currently experiencing academic "
            "challenges based on the analysed learning indicators. Early academic intervention, "
            "improved attendance, stronger study habits and regular teacher support are recommended."
        )

    elements.append(Paragraph(interpretation, normal))
    elements.append(Spacer(1, 18))

    elements.append(Paragraph("6. Report Information", heading))

    footer = Table(
        [
            ["Generated By", "EduInsight AI"],
            ["Prediction Model", "Support Vector Machine (SVM)"],
            ["Artificial Intelligence", "Groq GPT-OSS 20B"],
            ["Institution", "Faculty of Information Technology and Communication"],
            ["System", "EduInsight AI Student Performance Prediction System"],
            ["Generated Date", datetime.now().strftime("%d %B %Y")],
            ["Generated Time", datetime.now().strftime("%I:%M %p")],
        ],
        colWidths=[2.7 * inch, 3.9 * inch],
    )

    footer.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), HexColor("#0d6efd")),
        ("TEXTCOLOR", (0, 0), (0, -1), white),
        ("BACKGROUND", (1, 0), (1, -1), colors.whitesmoke),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
    ]))

    elements.append(footer)
    elements.append(Spacer(1, 20))

    disclaimer = """
<b>Disclaimer:</b><br/><br/>

This report has been automatically generated by the EduInsight AI Student
Performance Prediction System.

Prediction results are produced using a Support Vector Machine (SVM)
classification model, while personalised recommendations are generated
using the Groq GPT-OSS 20B large language model.

The generated insights are intended to assist teachers in monitoring
student academic performance and planning early interventions.
Final academic decisions should always be made by qualified educators
using their professional judgement.
"""

    elements.append(Paragraph(disclaimer, normal))
    doc.build(elements) 